# =====================================================================
#  Crossplane Claim — XPostgreSQLInstance
# =====================================================================
apiVersion: database.poc.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: dev-database
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    dbName: devdb-v2
    owner: devteam
  writeConnectionSecretToRef:
    name: dev-database-conn
    namespace: default
