# =====================================================================
#  Crossplane provider — XPostgreSQLInstance
# =====================================================================
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/tages/provider-postgresql:v0.1.0